---
- name: Install Ansible
  apt:
    name: 
      - ansible
      - sshpass
    state: present
    update_cache: yes

- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

