---
- name: Main Playbook Using Includes
  hosts: all
  become: yes

  tasks:
    - name: Include install tasks (static parse time)
      import_tasks: C1/Imports/roles/tasks/install_packages.yml

    - name: Include configuration tasks (static parse time)
      import_tasks: C1/Imports/roles/tasks/configure_service.yml

    - name: Include service start tasks (static parse time)
      import_tasks: C1/Imports/roles/tasks/start_service.yml

???


- name: Deploy Web Server Role
  hosts: all
  become: yes
  vars:
    web_server: nginx         # Or apache
    enable_firewall: true

  roles:
    - webserver

???

- name: Include a task file for each item
  include_tasks: "{{ item }}"
  loop:
    - install_nginx.yml
    - configure_firewall.yml



