Great question — **yes**, you **can absolutely `import_tasks` or `include_tasks` inside `pre_tasks`** in your playbooks!

This is super handy when you want to modularize pre-run checks, validations, or setup actions before your main tasks begin.

---

### ✅ Example: Using `import_tasks` in `pre_tasks`

```yaml
---
- name: Playbook with Imported Pre-Tasks
  hosts: all
  become: yes

  pre_tasks:
    - name: Import environment validation tasks
      import_tasks: tasks/precheck_environment.yml

    - name: Import SSH validation tasks
      import_tasks: tasks/precheck_ssh.yml

  roles:
    - webserver
```

---

### ✅ Example: Using `include_tasks` in `pre_tasks` (runtime conditional)

```yaml
---
- name: Playbook with Included Pre-Tasks
  hosts: all
  become: yes
  vars:
    check_environment: true

  pre_tasks:
    - name: Conditionally include pre-environment checks
      include_tasks: tasks/precheck_environment.yml
      when: check_environment

    - name: Include another pre-task at runtime
      include_tasks: tasks/precheck_network.yml
```

---

### 🧪 Why `import_tasks` vs `include_tasks` matters here

| Task Type      | Timing     | Can Use `when` | Example Use                          |
|----------------|------------|----------------|--------------------------------------|
| `import_tasks` | Parse-time | ❌ (mostly ignored) | Fixed pre-task sequence (always runs) |
| `include_tasks`| Run-time   | ✅ Yes          | Conditional pre-tasks or loops        |

---

### 📁 Example Task File: `tasks/precheck_environment.yml`

```yaml
---
- name: Check free disk space
  command: df -h /
  register: disk_usage

- name: Warn if free space is low
  debug:
    msg: "Low disk space warning: {{ disk_usage.stdout_lines }}"
  when: "'/dev/root' in disk_usage.stdout"
```

---

Let me know if you want this structured for reuse in a role’s `pre_tasks`, or with handler pre-flight checks too.

---
- name: Docker Swarm Deployment Playbook
  hosts: docker_swarm_nodes
  become: yes
  vars:
    docker_service_state: started

  pre_tasks:
    - name: Ensure Docker is installed
      package:
        name: docker.io
        state: present
      register: docker_installation

    - name: Ensure Docker service is enabled and running
      service:
        name: docker
        state: "{{ docker_service_state }}"
        enabled: true
      register: docker_service_status

    - name: Verify Docker is reachable
      command: docker info
      register: docker_info
      failed_when: docker_info.rc != 0
      changed_when: false

    - name: Display Docker environment validation summary
      debug:
        msg:
          - "Docker Installation: {{ 'Changed' if docker_installation.changed else 'Already installed' }}"
          - "Docker Service Status: {{ docker_service_status.state }}"
          - "Docker Info Command Output Successful."

  tasks:
    - name: Deploy Docker Swarm services
      command: docker stack deploy -c docker-compose.yml my_stack
      args:
        chdir: /home/ansible/docker_swarm/deployment
      register: deploy_result

    - name: Confirm Docker Swarm service deployment
      debug:
        msg: "{{ deploy_result.stdout }}"


---
- name: Main Playbook Using Includes
  hosts: all
  become: yes

  tasks:
    - name: Include install tasks (static parse time)
      import_tasks: C1/Imports/roles/tasks/install_packages.yml

    - name: Include configuration tasks (static parse time)
      import_tasks: C1/Imports/roles/tasks/configure_service.yml

    - name: Include service start tasks (static parse time)
      import_tasks: C1/Imports/roles/tasks/start_service.yml

???


- name: Deploy Web Server Role
  hosts: all
  become: yes
  vars:
    web_server: nginx         # Or apache
    enable_firewall: true

  roles:
    - webserver

???

- name: Include a task file for each item
  include_tasks: "{{ item }}"
  loop:
    - install_nginx.yml
    - configure_firewall.yml



