---
- name: Configure Site
  hosts: all
  become: true

  pre_tasks:
    - name: Import basic environment setup pretasks
      import_tasks: pretasks/C1_env_blk.yml

    - name: Include basic environment setup pretasks (conditionally executed)
      include_tasks: pretasks/C1_env_blk.yaml
      when: security_checks_enabled | default(true)

  tasks:
    - name: Import common server preparation tasks
      import_tasks: tasks/C1_envblk.yml

    - name: Include optional monitoring setup tasks
      include_tasks: tasks/C1_envblk.yaml
      when: monitoring_enabled | default(false)

  roles:
    - cold-start

