---
- name: Ensure Ansible is installed and set up initial inventory
  hosts: localhost
  become: yes
  tasks:

    - name: Ensure necessary system packages are installed
      apt:
        name:
          - ansible
        state: present
        update_cache: yes

    - name: Verify Ansible installation
      command: ansible --version
      register: ansible_version
      ignore_errors: yes  # To capture errors gracefully for debugging

    - name: Display Ansible version or error
      debug:
        msg: >
          {% if ansible_version.stdout is defined %}
            Ansible version: {{ ansible_version.stdout_lines }}
          {% elif ansible_version.stderr is defined %}
            Error: {{ ansible_version.stderr }}
          {% else %}
            Command failed with no output.
          {% endif %}

    - name: Ensure Ansible inventory directory exists
      file:
        path: /home/ansible/inventories
        state: directory
        mode: '0755'

    - name: Create initial Ansible inventory file
      copy:
        dest: /home/ansible/inventories/hosts.ini
        content: |
          [ansible-controller]
          Ansible-Con-troller ansible_host=192.168.0.100 ansible_user=ansible
        mode: '0644'

    - name: Display Inventory File Content
      command: cat /home/ansible/inventories/hosts.ini
      register: inventory_content

    - name: Show Inventory
      debug:
        msg: >
          {% if inventory_content.stdout is defined %}
            Inventory content: {{ inventory_content.stdout_lines }}
          {% elif inventory_content.stderr is defined %}
            Error: {{ inventory_content.stderr }}
          {% else %}
            Command failed with no output.
          {% endif %}

    - name: Generate SSH keypair (if not already created)
      command: ssh-keygen -t rsa -b 4096 -f /home/ansible/.ssh/id_rsa -N ''
      args:
        creates: /home/ansible/.ssh/id_rsa
      become_user: ansible

    - name: Ensure ~/.ssh directory exists
      file:
        path: /home/ansible/.ssh
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'

    - name: Read generated SSH public key
      command: cat /home/ansible/.ssh/id_rsa.pub
      register: ssh_pub_key
      become_user: ansible

    - name: Ensure Ansible user has SSH access on the controller
      authorized_key:
        user: ansible
        state: present
        key: "{{ ssh_pub_key.stdout }}"

    - name: Test SSH connectivity to Ansible Controller
      command: ssh -o StrictHostKeyChecking=no ansible@192.168.0.100 "echo 'SSH Connection Successful'"
      register: ssh_test
      ignore_errors: yes

    - name: Show SSH test result
      debug:
        msg: >
          {% if ssh_test.stdout is defined %}
            ssh test: {{ ssh_test.stdout_lines | default('SSH connection }}
          {% elif ssh_test.stderr is defined %}
            Error: {{ ssh_test.stderr | default('SSH connection test failed!') }}
          {% else %}
            Command failed with no output.
          {% endif %}
          
