---
- name: Docker Installation and Setup
  hosts: docker_hosts
  become: true

  pre_tasks:
    - name: Import system checks
      import_tasks: pre_tasks/check_system.yml

    - name: Include prerequisite tasks conditionally
      include_tasks: pre_tasks/setup_prerequisites.yml
      when: setup_prereqs | default(true)

  tasks:
    - name: Import tasks to manage Docker users
      import_tasks: tasks/docker_users.yml

    - name: Include Docker logging setup conditionally
      include_tasks: tasks/setup_logging.yml
      when: setup_logging | default(false)

  roles:
    - docker


---
- name: Configure Webservers
  hosts: webservers
  become: true

  pre_tasks:
    - name: Import basic environment setup tasks
      import_tasks: pre_tasks/setup_env.yml

    - name: Include security check tasks (conditionally executed)
      include_tasks: pre_tasks/security_checks.yml
      when: security_checks_enabled | default(true)

  tasks:
    - name: Import common server preparation tasks
      import_tasks: tasks/server_prep.yml

    - name: Include optional monitoring setup tasks
      include_tasks: tasks/monitoring.yml
      when: monitoring_enabled | default(false)

  roles:
    - webserver
