---
C1_host_vars:
  C1_ansible_controller: "Ansible-Con-troller"
  C1_omada_controller: "Omada-Con-troller"
  C1_venus_controller: "Venus-Con-troller"
  C1_main_controller: "Main-Con-troller"
  C1_main_console: "Main-Con-sole"
